- platform: template
  switches:
    template_samsung_tv:
      friendly_name: 'Samsung TV'
      value_template: "{{ not is_state('media_player.samsung_tv', 'off') }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.samsung_tv_power
      turn_off:
        - service: switch.turn_off
          entity_id: switch.samsung_tv_power
- platform: template
  switches:
    template_soniq_tv:
      friendly_name: 'Bedroom TV'
      value_template: "{% if states.media_player.chromecast_bedroom == none or is_state('media_player.chromecast_bedroom', 'unavailable') %}False{% else %}True{% endif %}"
      turn_on:
        - service: script.soniq_tv_power
      turn_off:
        - service: script.soniq_tv_power
# - platform: template
#   switches:
#     template_home_server:
#       friendly_name: 'Home Server'
#       value_template: "{{ is_state('sensor.hp_ilo_server_power', 'ON') or is_state('sensor.hp_ilo_server_power', 'on') }}"
#       turn_on:
#         - service: switch.turn_on
#           entity_id: switch.home_server
#       turn_off:
#         - service: switch.turn_off
#           entity_id: switch.home_server

########## Harmony Activity Switches ##########
- platform: template
  switches:
    template_harmony_power:
      friendly_name: 'Harmony On/Off'
      value_template: "{{ is_state('remote.living_room', 'on') }}"
      turn_on:
        - service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 13474528
      turn_off:
        - service: remote.turn_off
          entity_id: remote.living_room
- platform: template
  switches:
    template_harmony_fetch:
      friendly_name: 'Watch Fetch'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch Fetch') }}"
      turn_on:
        - service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 13474528
      turn_off:
        - service: remote.turn_off
          entity_id: remote.living_room
- platform: template
  switches:
    template_harmony_tvsurround:
      friendly_name: 'Watch TV with Surround'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'TV and surround') }}"
      turn_on:
        - service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 13915533
      turn_off:
        - service: remote.turn_off
          entity_id: remote.living_room
- platform: template
  switches:
    template_harmony_ps4:
      friendly_name: 'Play PS4'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Play PS4') }}"
      turn_on:
        - service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 13332151
      turn_off:
        - service: remote.turn_off
          entity_id: remote.living_room
- platform: template
  switches:
    template_harmony_netflix:
      friendly_name: 'Watch Netflix'
      value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch Netflix') }}"
      turn_on:
        - service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 13474528
      turn_off:
        - service: remote.turn_off
          entity_id: remote.living_room
### Alarm ###
- platform: template
  switches:
    template_alarm:
      friendly_name: 'Alarm System'
      value_template: "{{ is_state('binary_sensor.konnected_zone_6', 'off') }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.alarm_toggle
      turn_off:
        - service: switch.turn_on
          entity_id: switch.alarm_toggle