- platform: bom
  station: !secret bom_station
  monitored_conditions:
    - apparent_t
    # - cloud
    # - cloud_base_m
    # - cloud_oktas
    # - cloud_type_id
    # - cloud_type
    # - delta_t
    # - gust_kmh
    # - gust_kt
    - air_temp
    # - dewpt
    # - press
    # - press_qnh
    # - press_msl
    # - press_tend
    - rain_trace
    - rel_hum
    # - sea_state
    # - swell_dir_worded
    # - swell_height
    # - swell_period
    # - vis_km
    # - weather
    # - wind_dir
    # - wind_spd_kmh
    # - wind_spd_kt

# - platform: bom_forecast
#   product_id: IDV10450
#   name: Melbourne
#   forecast_days: 5
#   rest_of_today: True
#   friendly: False
#   friendly_state_format: '{max}, {summary}'
#   monitored_conditions:
#     - 'max'
#     - 'min'
#     - 'chance_of_rain'
#     - 'possible_rainfall'
#     - 'summary'
#     - 'detailed_summary'

# - platform: darksky
#   api_key: !secret darksky_api
#   forecast:
#       - 1
#       - 2
#       - 3
#       - 4
#       - 5
#   monitored_conditions:
#       - icon
#       - summary
#       - nearest_storm_distance
#       - nearest_storm_bearing
#       - humidity
#       - temperature
#       - temperature_high
#       - temperature_low
#       - apparent_temperature
#       - apparent_temperature_high
#       - apparent_temperature_low
#       - wind_speed
#       - wind_bearing
#       - precip_type
#       - precip_probability
#       - precip_accumulation
#       - precip_intensity
#       - precip_intensity_max
#       - uv_index
#       - daily_summary
#       - pressure
#       - visibility
#   scan_interval:
#       minutes: 5
