- platform: systemmonitor
  resources:
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: memory_use
    - type: memory_free    
    - type: memory_use_percent
    - type: processor_use
    - type: network_in
      arg: wlan0
    - type: network_out
      arg: wlan0
    - type: packets_in
      arg: wlan0
    - type: packets_out
      arg: wlan0
    - type: ipv4_address
      arg: wlan0
    - type: last_boot
# - platform: command_line
  # name: SSL cert expiry
  # unit_of_measurement: days
  # scan_interval: 10800
  # command: !secret ssl_command
