- platform: mqtt
  name: Garage Main
  state_topic: "cmnd/garage1_state/POWER2"
  command_topic: "cmnd/garage1/POWER"
  availability_topic: "tele/garage1/LWT"
  payload_open: "ON"
  payload_close: "ON"
  payload_stop: "ON"
  state_open: "OFF"
  state_closed: "ON"
  payload_available: "Online"
  payload_not_available: "Offline"
  optimistic: false
  device_class: garage

- platform: mqtt
  name: Garage Rear
  state_topic: "cmnd/garage2_state/POWER2"
  command_topic: "cmnd/garage2/POWER"
  availability_topic: "tele/garage2/LWT"
  payload_open: "ON"
  payload_close: "ON"
  payload_stop: "ON"
  state_open: "OFF"
  state_closed: "ON"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: garage