### Sonoff Rleays ###
- platform: mqtt
  name: "Outdoor LED"
  state_topic: "stat/brilliant02/RESULT"  
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/brilliant02/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/brilliant02/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
  json_attributes_topic: "tele/brilliant02/STATE"
  json_attributes_template: "{{ value_json | tojson }}"

- platform: mqtt
  name: "Play Room Lamp"
  state_topic: "stat/brilliant03/RESULT"  
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/brilliant03/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/brilliant03/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
  json_attributes_topic: "tele/brilliant03/STATE"
  json_attributes_template: "{{ value_json | tojson }}"

### Mirabella Globes ###
# - platform: mqtt
#   name: Back Hallway
#   command_topic: "cmnd/bulb1/POWER"
#   state_topic: "tele/bulb1/STATE"
#   state_value_template: "{{value_json.POWER}}"
#   availability_topic: "tele/bulb1/LWT"
#   brightness_command_topic: "cmnd/bulb1/Dimmer"
#   brightness_state_topic: "tele/bulb1/STATE"
#   brightness_scale: 100
#   on_command_type: "brightness"
#   brightness_value_template: "{{value_json.Dimmer}}"
#   payload_on: "ON"
#   payload_off: "OFF"
#   payload_available: "Online"
#   payload_not_available: "Offline"
#   qos: 1
#   retain: false

# - platform: mqtt
#   name: Front Porch
#   command_topic: "cmnd/bulb2/POWER"
#   state_topic: "tele/bulb2/STATE"
#   state_value_template: "{{value_json.POWER}}"
#   availability_topic: "tele/bulb2/LWT"
#   brightness_command_topic: "cmnd/bulb2/Dimmer"
#   brightness_state_topic: "tele/bulb2/STATE"
#   brightness_scale: 100
#   on_command_type: "brightness"
#   brightness_value_template: "{{value_json.Dimmer}}"
#   payload_on: "ON"
#   payload_off: "OFF"
#   payload_available: "Online"
#   payload_not_available: "Offline"
#   qos: 1
#   retain: false

# - platform: mqtt
#   name: Guest Bedroom
#   command_topic: "cmnd/bulb4/POWER"
#   state_topic: "tele/bulb4/STATE"
#   state_value_template: "{{value_json.POWER}}"
#   availability_topic: "tele/bulb4/LWT"
#   brightness_command_topic: "cmnd/bulb4/Dimmer"
#   brightness_state_topic: "tele/bulb4/STATE"
#   brightness_scale: 100
#   on_command_type: "brightness"
#   brightness_value_template: "{{value_json.Dimmer}}"
#   color_temp_command_topic: "cmnd/bulb4/CT"
#   color_temp_state_topic: "tele/bulb4/STATE"
#   color_temp_value_template: "{{value_json.CT}}"
#   payload_on: "ON"
#   payload_off: "OFF"
#   payload_available: "Online"
#   payload_not_available: "Offline"
#   qos: 1
#   retain: false

# - platform: mqtt
#   name: Pantry Light
#   command_topic: "cmnd/bulb3/POWER"
#   state_topic: "tele/bulb3/STATE"
#   state_value_template: "{{value_json.POWER}}"
#   availability_topic: "tele/bulb3/LWT"
#   brightness_command_topic: "cmnd/bulb3/Dimmer"
#   brightness_state_topic: "tele/bulb3/STATE"
#   brightness_scale: 100
#   on_command_type: "brightness"
#   brightness_value_template: "{{value_json.Dimmer}}"
#   color_temp_command_topic: "cmnd/bulb3/CT"
#   color_temp_state_topic: "tele/bulb3/STATE"
#   color_temp_value_template: "{{value_json.CT}}"
#   payload_on: "ON"
#   payload_off: "OFF"
#   payload_available: "Online"
#   payload_not_available: "Offline"
#   qos: 1
#   retain: false