- alias: 'Mum Home'
  hide_entity: True
  trigger:
    platform: state
    entity_id: device_tracker.mums_lg_g4
    to: 'home'
  action:
    - service: notify.html5
      data_template:
        message: "{{now().strftime('%-d-%b-%Y %H:%M:%S')}}: Mum arrived"

- alias: 'Mum Not Home'
  hide_entity: True
  trigger:
    platform: state
    entity_id: device_tracker.mums_lg_g4
    to: 'not_home'
  action:
    - service: notify.html5
      data_template:
        message: "{{now().strftime('%-d-%b-%Y %H:%M:%S')}}: Mum left"
