- alias: Toggle Bedroom Light on Single Press
  hide_entity: True
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.xiaomi_switch_1
        click_type: single
  action:
    service: light.toggle
    entity_id: light.Bedroom

- alias: Turn Off Everything on Long Press
  hide_entity: True
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.xiaomi_switch_1
        click_type: long_click_press
  action:
    service: switch.turn_off
    entity_id: switch.master_switch
    
# - alias: Toggle couch light on double click
  # hide_entity: True
  # trigger:
    # platform: event
    # event_type: click
    # event_data:
      # entity_id: binary_sensor.xiaomi_switch_1
      # click_type: double
  # action:
    # service: switch.toggle
    # entity_id: switch.wall_switch_right_158d000xxxxx01
