- platform: ping
  name: Online
  host: 8.8.8.8
  count: 5
  scan_interval: 300

- platform: mqtt
  name: "Car Sensor"
  device_class: presence
  state_topic: "tele/garage1/SENSOR"
  value_template: >-
    {% if value_json.SR04.Distance | float >= 220 -%}
      OFF
    {%- else -%}
      ON
    {%- endif %}
  availability_topic: "tele/garage1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  json_attributes_topic: "tele/garage1/SENSOR"
  json_attributes_template: "{{ value_json.SR04 | tojson }}"

# - platform: template
#   sensors: 
#     anyone_home:
#       friendly_name: "Anyone Home"
#       # value_template: "{{ states.person | selectattr('state','eq','home') | list | count > 0 }}"
#       value_template: "{{ is_state('person.nick','home') or  is_state('person.ashlei','home') or is_state('person.cath','home') or is_state('person.liza','home')}}"
#       availability_template: "{{ not(is_state('device_tracker.main_uap_pro','unavailable')) }}"
#       device_class: presence
