- platform: ffmpeg
  input: !secret cam1
  name: Study
- platform: ffmpeg
  input: !secret cam2
  name: Nursery
- platform: ffmpeg
  input: !secret cam3
  name: Kitchen
- platform: ffmpeg
  input: !secret cam4
  name: dafang1
- platform: ffmpeg
  input: !secret cam5
  name: dafang2
- platform: ffmpeg
  input: !secret reolink1
  name: Front 1
- platform: ffmpeg
  input: !secret reolink2
  name: Front 2
- platform: ffmpeg
  input: !secret reolink3
  name: Deck
- platform: ffmpeg
  input: !secret reolink4
  name: Side
- platform: ffmpeg
  input: !secret reolink5
  name: Backyard