- platform: smartir
  name: Bedroom
  unique_id: bedroom
  device_code: 1022
  controller_data: remote.bedroom_remote
  temperature_sensor: sensor.xiaomi_temp_bedroom
  humidity_sensor: sensor.xiaomi_humidity_bedroom
  
- platform: harmony_ac
  name: Living Room
  remote_entity: remote.living_room
  device_id: 58354062
  min_temp: 18
  max_temp: 30
  target_temp: 20
  target_temp_step: 1
  temp_sensor: sensor.xiaomi_temp_main
  customize:
    operations:
      - cool
      - dry
      - heat
    fan_modes:
      - auto
      - low
      - med
      - high